### ISSUE TITLE
Question: How do you handle the 10k transaction limit with etherscan?

### ISSUE THREAD

**Issue by brendanmc6** [memo/eco-nft#16]
Just a question. I want the open source eth calculator to handle > 10k transactions but I'm not allowed to paginate past 10k. I have a solution in mind, but then I thought, maybe this is a problem Memo has already solved...

**Comment by brendanmc6** [comment]
haha that's exactly the same solution I had in mind. Brilliant man thank you!

**Comment by brendanmc6** [comment]
@memo oh one more thing, how do you determine the end block #? I was thinking about using a separate API to identify the latest ethereum block-height (most recent block #).

**Comment by memo** [comment]
I use https://web3js.readthedocs.io/en/v1.3.4/ anyway, so I read the most recent block from there.
