### ISSUE TITLE
add Eporio

### ISSUE THREAD

**Issue by alexsyo** [memo/eco-nft#7]
Hi, I would like to thank you for your effort in spreading knowledge on the sustainability of projects,

I am here to present Eporio, https://epor.io which is a marketplace living on the xDai chain whose total usage is comparable to 2 U.S. households as described here:

https://www.xdaichain.com/about-xdai/news-and-information/xdai-energy-efficiency

I think it would be a good fit for this list =)

**Comment by memo** [comment]
awesome thx, I've added it.
