### ISSUE TITLE
add SIGN Art

### ISSUE THREAD

**Issue by christopheSeeka** [memo/eco-nft#8]
Hi, SIGN Art developer here, i believe our platform would fit well in your list, here the detail:

SIGN Art curated marketplace for digital art
https://sign-art.app/
Blockchain: Waves Protocol (WAVES) 
Consensus: Lease PoS
Curated
Minting free on buy request

Let me know if needs more info or prefer a pull request.

**Comment by memo** [comment]
awesome thx, if you can send PR that'd be great
